### ISSUE TITLE
Métodos POST o GET en los controladores

### ISSUE THREAD

**Issue by siberiaaa** [G3-Graco/laboratorio-blazor-nice-team#2]
Tengo entendido que cuando uno utiliza get uno no debe enviar información, es por esto que para la consulta de cliente en la API utilicé un método POST, ya que estaba enviando el int idsesionusuario a través del query. No sé si esta es la mejor manera de abordarlo.

Además ahora pasa que en el lado de la app blazor, el consumidor de las peticiones http, sobreentiende que no hay contenido si es un método GET o DELETE. Ahora no sé, si el hecho de que haya información en el query cuenta como "contenido". 

Y además, sabe que en el método execute del consumidor también dependiendo de si es GET o DELETE no hace la serialización d contenido porque en teoría no hay.

Entonces estoy un poco enredada en eso, si lo del query cuenta como contenido y cuál sería la mejor manera de consumirlo, y qué método debería ser en el controlador y bueno, etc...

Una de las fotos es el controlador de cliente en el endpoint consultar cliente (API), y la otra foto sería el método para consultar cliente en el servicio de cliente (APP)

![IMG-20240416-WA0043.jpg](https://github.com/G3-Graco/laboratorio-blazor-nice-team/assets/128342488/b8e97e02-e1cd-43d1-a112-9bdc454e4a38)

![IMG-20240416-WA0044.jpg](https://github.com/G3-Graco/laboratorio-blazor-nice-team/assets/128342488/becca989-5a72-42e7-a8f8-78fd3377f8d9)

**Comment by GGimenezG** [comment]
El método `GET `efectivamente no permite que se le asigne un contenido, este contenido se refiere a la presencia del `BODY `de la petición `HTTP` 

Cuando quieres hacer una consulta de alguna entidad, pero esta consulta requiere de parámetros por ejemplo `idusuariosesion` tienes dos formas de abordarlas, la primera, hacerla parte del `PATH `como vimos en el desarrollo del curso con los métodos de `GetById` o puedes hacerlo con los `query params` estos últimos son opcionales en una `URL` no pertenecen al `PATH ` como tal; pero pueden ser accedidas en la API, los datos los configurarias desde tu servicio

EJ
`
respuesta = await Consumidor.Execute<Usuario, RespuestaAPI<RespuestaIniciarSesion>>($"https://localhost:7181/api/Usuario/iniciosesion?idusuariosesion={variableusuarioid}", MethodHttp.POST, usuario);`

**Comment by siberiaaa** [comment]
Bueno hasta ahora así lo estoy manejando, solo era para confirmar que no hubiese ningún problema que yo pasara un null como objeto para el body ya que solo estaba pasando el query por la url.

**Comment by GGimenezG** [comment]
Por las dudas, si vas a hacer una consulta (traer datos de la base) aunque sea con filtros usa el método GET en lugar del método POST

**Comment by GGimenezG** [comment]
Exacto, pasar parámetros a un método GET no quita que siga siendo para consulta
