### ISSUE TITLE
new IEnumerable?

### ISSUE THREAD

**Issue by siberiaaa** [G3-Graco/laboratorio-blazor-nice-team#4]
Quería utilizar el IEnumerable para mostrar información en el componente. No sé por qué no me deja hacer un new() etc. Busqué un poco en internet al respecto, pero la verdad no entendí por qué no deja hacer eso.
Por mientras utilizaré la estructura de lista no más, pero igual tengo esa duda.

![image](https://github.com/G3-Graco/laboratorio-blazor-nice-team/assets/128342488/92826201-72e2-460d-8c4e-3a5b4f937892)

**Comment by GGimenezG** [comment]
Un IEnumerable digamos es una "super clase", que agrupa varios tipos de datos como listas (List<T>) y colecciones (Collection<T>) entonces crear una instancia de un Enumerable no sería posible por la complejidad de la definición misma, mas aún IEnumerable es una Interfaz como interfaz se le pueden definir cosas pero una interfaz esta definición de superClase, pero una interfaz no se puede instanciar, es solo un contrato que le indica a las clases que la implementes el conjunto de definiciones que debe cumplir

**Comment by siberiaaa** [comment]
Tiene sentido
